-- 1. Tábla törlése (ha szükséges)
DROP TABLE IF EXISTS PARKING_SPOT;

-- 2. Új tábla létrehozása a megfelelő mezőkkel
CREATE TABLE PARKING_SPOT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SPOT_NUMBER INT NOT NULL,
    LICENSE_PLATE VARCHAR(20),
    OCCUPIED BOOLEAN NOT NULL DEFAULT FALSE,
    CAR_TYPE VARCHAR(50),
    COLOR VARCHAR(30)
);

-- 3. Kezdeti adatok beszúrása
INSERT INTO PARKING_SPOT (SPOT_NUMBER, OCCUPIED) VALUES
(1, FALSE),
(2, FALSE),